import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Subscription",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="h-screen w-screen bg-gray-100 overflow-x-hidden">
        {children}
      </body>
    </html>
  );
}
